import { useState } from "react";

import type {
  MemoryReuseEvent,
  RelayMemory,
} from "../types/api";

interface ExportMemoryButtonProps {
  memory: RelayMemory;
  reuseEvents: MemoryReuseEvent[];
}

type ExportState =
  | "idle"
  | "exporting"
  | "exported"
  | "failed";

function formatLabel(value: string): string {
  return value
    .replaceAll("_", " ")
    .replace(/\b\w/g, (letter) =>
      letter.toUpperCase(),
    );
}

function formatDate(value: string | null): string {
  if (!value) {
    return "Not available";
  }

  const date = new Date(value);

  if (Number.isNaN(date.getTime())) {
    return value;
  }

  return new Intl.DateTimeFormat(undefined, {
    dateStyle: "medium",
    timeStyle: "short",
  }).format(date);
}

function formatConfidence(
  value: number | null,
): string {
  if (value === null) {
    return "Unknown";
  }

  return `${Math.round(value * 100)}%`;
}

function sanitizeFilename(value: string): string {
  const normalized = value
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");

  return normalized || "relay-memory";
}

function createReuseHistory(
  reuseEvents: MemoryReuseEvent[],
): string {
  if (reuseEvents.length === 0) {
    return "This memory has not yet been reused.";
  }

  return reuseEvents
    .map(
      (event, index) => `
### Reuse ${index + 1}

- **Investigation ID:** ${event.investigation_id}
- **Reuse type:** ${formatLabel(event.reuse_type)}
- **Similarity:** ${formatConfidence(
        event.similarity_score,
      )}
- **Accepted:** ${event.accepted ? "Yes" : "No"}
- **Estimated steps skipped:** ${
        event.estimated_steps_skipped
      }
- **Estimated time saved:** ${
        event.estimated_time_saved_minutes
      } minutes
- **Created:** ${formatDate(event.created_at)}

${event.agent_explanation}
`.trim(),
    )
    .join("\n\n");
}

function createMarkdownReport(
  memory: RelayMemory,
  reuseEvents: MemoryReuseEvent[],
): string {
  const keywords =
    memory.keywords.length > 0
      ? memory.keywords
          .map((keyword) => `- ${keyword}`)
          .join("\n")
      : "No keywords recorded.";

  const relatedAssets =
    memory.related_asset_urns.length > 0
      ? memory.related_asset_urns
          .map((assetUrn) => `- \`${assetUrn}\``)
          .join("\n")
      : "No related assets recorded.";

  const evidence =
    memory.evidence_ids.length > 0
      ? memory.evidence_ids
          .map((evidenceId) => `- ${evidenceId}`)
          .join("\n")
      : "No evidence records preserved.";

  return `# ${memory.title}

> Verified organizational memory exported from Relay.

## Summary

${memory.summary}

## Classification

- **Memory key:** ${memory.memory_key}
- **Version:** ${memory.version}
- **Verification status:** ${formatLabel(
    memory.verification_status,
  )}
- **Incident type:** ${formatLabel(memory.incident_type)}
- **Confidence:** ${formatConfidence(memory.confidence)}
- **Primary asset:** \`${memory.primary_asset_urn}\`
- **Originating investigation:** ${
    memory.originating_investigation_id
  }
- **Created:** ${formatDate(memory.created_at)}
- **Verified:** ${formatDate(memory.verified_at)}
- **Updated:** ${formatDate(memory.updated_at)}

## Root Cause

${memory.root_cause}

## Verified Resolution

\`\`\`
${memory.resolution}
\`\`\`

## Retrieval Keywords

${keywords}

## Related DataHub Assets

${relatedAssets}

## Supporting Evidence

${evidence}

## Reuse History

${createReuseHistory(reuseEvents)}

---

Generated by Relay — collaborative operational memory for AI agents.
`;
}

export default function ExportMemoryButton({
  memory,
  reuseEvents,
}: ExportMemoryButtonProps) {
  const [exportState, setExportState] =
    useState<ExportState>("idle");

  function handleExport() {
    setExportState("exporting");

    try {
      const report = createMarkdownReport(
        memory,
        reuseEvents,
      );

      const blob = new Blob([report], {
        type: "text/markdown;charset=utf-8",
      });

      const objectUrl = URL.createObjectURL(blob);
      const anchor = document.createElement("a");

      anchor.href = objectUrl;
      anchor.download = `${sanitizeFilename(
        memory.title,
      )}-relay-memory.md`;

      document.body.appendChild(anchor);
      anchor.click();
      document.body.removeChild(anchor);

      URL.revokeObjectURL(objectUrl);

      setExportState("exported");

      window.setTimeout(() => {
        setExportState("idle");
      }, 2000);
    } catch {
      setExportState("failed");

      window.setTimeout(() => {
        setExportState("idle");
      }, 2000);
    }
  }

  const label =
    exportState === "exporting"
      ? "Preparing report…"
      : exportState === "exported"
        ? "Report downloaded"
        : exportState === "failed"
          ? "Export failed"
          : "Download report";

  return (
    <button
      className={[
        "relay-export-button",
        exportState === "exported"
          ? "is-exported"
          : "",
        exportState === "failed"
          ? "is-failed"
          : "",
      ]
        .filter(Boolean)
        .join(" ")}
      type="button"
      disabled={exportState === "exporting"}
      onClick={handleExport}
    >
      <span aria-hidden="true">
        {exportState === "exported" ? "✓" : "↓"}
      </span>

      {label}
    </button>
  );
}